name: Build and test solution
permissions: read-all

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**
  workflow_call: {}
  workflow_dispatch: {}

env:
  CI: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'STN-DTS/canadian-dental-care-plan' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: frontend
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            src:
              - frontend/**
      - id: gitops
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            src:
              - gitops/**
      - id: infrastructure
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        with:
          filters: |
            src:
              - infrastructure/**
    outputs:
      frontend-changed: ${{ steps.frontend.outputs.src }}
      gitops-changed: ${{ steps.gitops.outputs.src }}
      infrastructure-changed: ${{ steps.infrastructure.outputs.src }}

  test-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.x
      - run: npm clean-install
        working-directory: frontend/
      - run: npm run format:check
        working-directory: frontend/
      - run: npm run typecheck
        working-directory: frontend/
      - run: npm run lint:eslint
        working-directory: frontend/
      - run: npm run test:unit:coverage
        working-directory: frontend/
      - run: npm run build
        working-directory: frontend/
      - run: npx playwright install chromium --with-deps
        working-directory: frontend/
      - run: npm run test:e2e:smoke
        working-directory: frontend/
  build-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26.x
      - run: npm clean-install
        working-directory: frontend/
      - run: podman build --file dockerfile .
        working-directory: frontend/
