name: Nightly e2e tests (main & release)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

env:
  CI: true

permissions: read-all

jobs:
  run-e2e-tests:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: frontend/package.json
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare --activate
        working-directory: frontend/
      - name: Verify versions
        run: |
          node -v
          pnpm -v
        working-directory: frontend/
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend/
      - name: Build frontend
        run: pnpm run build
        working-directory: frontend/
      - name: Install Playwright dependencies
        run: pnpm exec playwright install chromium --with-deps
        working-directory: frontend/
      - name: Run e2e tests
        run: pnpm run test:e2e
        working-directory: frontend/
